version: '3.8'

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      # Opcional: Pasar UID/GID del host para construir la imagen y evitar problemas de permisos
      # args:
      #   UID: ${UID:-1000}
      #   GID: ${GID:-1000}
    container_name: php_apache_app_gym
    ports:
      - "${APP_PORT:-80}:80" # Mapea el puerto 80 del contenedor (Apache) al puerto especificado en .env o 80 por defecto
    volumes:
      - ./src:/var/www/html # Monta el c贸digo fuente actual en el DocumentRoot de Apache
      # Opcional: Si se quiere un log de Apache persistente
      # - ./docker/apache/logs:/var/log/apache2
    restart: unless-stopped
    environment:
      # Variables de entorno para la aplicaci贸n PHP, ej:
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      DB_HOST: db # Nombre del servicio de la base de datos
      DB_PORT: ${DB_PORT_INTERNAL:-3306}
      DB_DATABASE: ${DB_DATABASE:-gym_db}
      DB_USERNAME: ${DB_USERNAME:-gym_user}
      DB_PASSWORD: ${DB_PASSWORD:-gym_password}
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0 # O postgres:15-alpine, o la versi贸n que se necesite
    container_name: db_gym
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-gym_db}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootsecret}
      MYSQL_USER: ${DB_USERNAME:-gym_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-gym_password}
      # Para PostgreSQL:
      # POSTGRES_DB: ${DB_DATABASE:-gym_db}
      # POSTGRES_USER: ${DB_USERNAME:-gym_user}
      # POSTGRES_PASSWORD: ${DB_PASSWORD:-gym_password}
    volumes:
      - db_data_gym:/var/lib/mysql # Para MySQL
      # - db_data_gym:/var/lib/postgresql/data # Para PostgreSQL
      # Opcional: Montar scripts de inicializaci贸n SQL
      # - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT_EXTERNAL:-3306}:3306" # Mapea el puerto 3306 del contenedor a uno en el host (configurable)
      # - "${DB_PORT_EXTERNAL:-5432}:5432" # Para PostgreSQL
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data_gym: # Volumen para persistir los datos de la base de datos
    driver: local
